### ISSUE TITLE
i cant handle it

### ISSUE THREAD

**Issue by mr3iscuit** [deni2312/Telegram-Bot-Api-Cpp#4]
Dirty/jsoncpp/include -std=gnu++20
bot.cpp:16:19: error: reference to type 'const std::function<void (const Telegram::Bot::Types::API &, const Telegram::Bot::Types::MessageReceive &)>' (aka 'const function<void (const Telegram::Bot::Types::API &, const Json::Value &)>') could not bind to an lvalue of type 'void (Telegram::Bot::Types::API &, Telegram::Bot::Types::MessageReceive &)' (aka 'void (Telegram::Bot::Types::API &, Json::Value &)')
        handler.callback(sendSomething);
                         ^~~~~~~~~~~~~
/home/biscuit/Dirty/Telegram-Bot-Api-Cpp/telegram/include/TelegramAPI.h:24:124: note: passing argument to parameter 'func' here
                        void callback(const std::function<void(const Telegram::Bot::Types::API&, const Telegram::Bot::Types::MessageReceive&)>& func);
                                                                                                                                                ^
1 error generated.

**Comment by deni2312** [comment]
Please give more contest to the issue, an idea would be to post the code that you have tried
