### ISSUE TITLE
Request for Method removeEvent() Implementation Return

### ISSUE THREAD

**Issue by Seryy-code** [deni2312/Telegram-Bot-Api-Cpp#7]
I am writing to seek assistance regarding a challenge I've encountered while working with the API TgBot.

The issue I'm facing pertains to the handling of user messages within the bot. Specifically, there are instances where I need to process a message from a user only once, but due to the perpetual operation of the onAnyMessage() method, achieving this becomes problematic.

Here is an example of the code snippet I'm struggling with:
```
bot.getEvents().onAnyMessage([&bot, &messageProcessed](TgBot::Message::Ptr message) {
    std::string text = message->text;
    std::cout << text ;
});
std::cout<<"The code will no longer work";
```
As you can see, the onAnyMessage() method continuously listens for incoming messages, making it challenging to handle a message only once and proceed with the rest of the code execution.

Perhaps I haven't thoroughly reviewed the documentation.

I would greatly appreciate your guidance on how to resolve this issue. Is there a way to use this method to capture a message just once and then unsubscribe from further message events? Alternatively, are there any alternative approaches or methods that I could employ to achieve the desired behavior?

Thank you very much for your time and assistance. Your expertise in this matter would be immensely valuable to me.

**Comment by Seryy-code** [comment]
And if I haven't explained my issue clearly, please let me know, and I'll rephrase it.

**Comment by deni2312** [comment]
You might use a database where are stored users that have consumed the message, that's the only way
